name: inova-api-deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Build the project
      run: npm run build

    - name: Copy dist folder with SSH
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./dist/"
        REMOTE_HOST: "ec2-18-188-56-228.us-east-2.compute.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/home/ec2-user/app"